# Generated by Django 4.0.5 on 2022-07-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='street',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartments.street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='compound',
            field=models.CharField(max_length=100),
        ),
    ]
