# Generated by Django 4.0.5 on 2022-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_street_alter_apartment_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
