# Generated by Django 4.0.5 on 2022-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_alter_street_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('taken', 'Taken')], default='free', max_length=15),
        ),
    ]
