# Generated by Django 4.0.5 on 2022-07-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupant',
            old_name='user',
            new_name='occupant',
        ),
    ]
