# Generated by Django 4.0.6 on 2022-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_apartment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='price',
        ),
        migrations.AddField(
            model_name='apartmenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=20),
        ),
    ]
