# Generated by Django 4.0.6 on 2022-08-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_remove_apartment_price_apartmenttype_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupant',
            name='assigned_by',
        ),
    ]
