# Generated by Django 4.0.6 on 2022-08-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='last_updated',
        ),
    ]
