# Generated by Django 4.0.6 on 2022-08-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_remove_paymentdetail_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='resident',
            new_name='occupant',
        ),
    ]
