# Generated by Django 4.0.6 on 2022-08-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_rename_user_payment_occupant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user',
            new_name='occupant',
        ),
    ]
